<a href="https://colab.research.google.com/github/Eva360563/fundamental/blob/main/MLDL_Lab01_Ex01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals Exercises




### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch
# Create random tensor
tensor = torch.rand(7,7)
print(tensor)

tensor([[3.5407e-01, 2.1936e-01, 1.2459e-01, 5.5287e-01, 4.0739e-01, 6.5769e-01,
         8.2555e-01],
        [1.4676e-01, 2.0029e-01, 9.6427e-01, 5.6542e-01, 6.8622e-01, 8.0770e-01,
         3.5903e-01],
        [5.6982e-02, 3.7502e-01, 8.1932e-01, 3.0676e-01, 8.0725e-02, 1.2486e-01,
         1.6322e-02],
        [5.6937e-01, 9.3726e-01, 6.6429e-01, 1.2707e-01, 6.6667e-01, 8.6970e-01,
         6.4400e-01],
        [9.0065e-01, 2.2861e-01, 6.8733e-01, 4.2361e-04, 9.4036e-01, 6.6915e-02,
         6.8292e-01],
        [5.7509e-01, 1.6171e-01, 8.5195e-01, 3.0151e-01, 5.8214e-02, 1.5679e-01,
         7.7307e-01],
        [4.3584e-01, 9.0712e-02, 3.6775e-01, 8.3326e-02, 7.3947e-01, 4.2072e-01,
         9.8637e-01]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor2= torch.rand(1,7)
print(tensor2)
# Perform matrix multiplication
mult= tensor.matmul(tensor2.T)
mult

tensor([[0.6043, 0.8410, 0.1866, 0.0739, 0.5440, 0.5043, 0.4949]])


tensor([[1.4244],
        [1.4371],
        [0.6403],
        [2.3856],
        [1.7481],
        [1.1581],
        [1.5170]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)


# Create two random tensors
tensor = torch.rand(7,7)
tensor2= torch.rand(1,7)


# Matrix multiply tensors
mult= tensor.matmul(tensor2.T)
mult

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [7]:
# Set random seed
torch.manual_seed(1234)
# Check for access to GPU
device = torch.device("cuda")
# Create two random tensors on GPU
tensorA = torch.rand(2,3).to(device)
tensorB= torch.rand(2,3).to(device)
print(tensorA)
print(tensorB)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [9]:
# Perform matmul on tensor_A and tensor_B
mult= tensorA.matmul(tensorB.T)
print(mult)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [13]:
# Find max
max= torch.max(mult)
print(max)
# Find min
min= torch.min(mult)
print(min)

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [14]:
# Find arg max
max= torch.argmax(mult)
print(max)

# Find arg min
min= torch.argmin(mult)
print(min)

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [15]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor= torch.rand(1,1,1,10)

# Remove single dimensions
tensor1= tensor.squeeze()


# Print out tensors and their shapes
print(tensor, tensor.shape)
print(tensor1, tensor1.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
